version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trucking_db
    ports:
      - "5432:5432"
    volumes:
      - db_storage:/var/lib/postgresql/data
volumes:
  db_storage: