# Generated by Django 5.2.7 on 2025-10-10 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_distance_miles", models.FloatField()),
                (
                    "total_duration_hours",
                    models.FloatField(help_text="Total elapsed time including breaks"),
                ),
                (
                    "total_driving_hours",
                    models.FloatField(help_text="Actual driving time"),
                ),
                (
                    "total_on_duty_hours",
                    models.FloatField(help_text="Driving + loading/unloading"),
                ),
                (
                    "total_off_duty_hours",
                    models.FloatField(help_text="Rest breaks and sleeper berth"),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("warning", "Warning"),
                        ],
                        default="compliant",
                        max_length=20,
                    ),
                ),
                ("compliance_notes", models.TextField(blank=True)),
                (
                    "mapbox_route_geometry",
                    models.JSONField(
                        blank=True,
                        help_text="GeoJSON geometry from MapBox Directions API",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(help_text="Order of stop in route (0-indexed)"),
                ),
                (
                    "stop_type",
                    models.CharField(
                        choices=[
                            ("current", "Current Location"),
                            ("pickup", "Pickup"),
                            ("dropoff", "Dropoff"),
                            ("fuel", "Fuel Stop"),
                            ("30min_break", "30-Minute Break"),
                            ("10hr_break", "10-Hour Rest"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=500)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "place_id",
                    models.CharField(
                        blank=True,
                        help_text="MapBox place ID if available",
                        max_length=255,
                    ),
                ),
                ("arrival_time", models.DateTimeField()),
                ("departure_time", models.DateTimeField()),
                (
                    "duration_minutes",
                    models.IntegerField(help_text="How long stopped here"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "miles_from_previous",
                    models.FloatField(
                        default=0, help_text="Distance from previous stop"
                    ),
                ),
                (
                    "cumulative_miles",
                    models.FloatField(
                        default=0, help_text="Total miles driven up to this stop"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "ordering": ["route", "sequence"],
                "unique_together": {("route", "sequence")},
            },
        ),
    ]
