# Generated by Django 5.2.7 on 2025-10-10 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.IntegerField(help_text="Day 1, Day 2, etc.")),
                ("log_date", models.DateField()),
                (
                    "total_driving_hours",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "total_on_duty_hours",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "total_off_duty_hours",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "total_sleeper_berth_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("start_location", models.CharField(max_length=500)),
                ("end_location", models.CharField(max_length=500)),
                ("total_miles", models.FloatField()),
                ("is_compliant", models.BooleanField(default=True)),
                (
                    "violations",
                    models.JSONField(
                        blank=True, default=list, help_text="List of any HOS violations"
                    ),
                ),
                (
                    "log_grid_data",
                    models.JSONField(
                        blank=True,
                        help_text="24-hour grid data for visual ELD log (15-minute intervals)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["trip", "day_number"],
                "unique_together": {("trip", "day_number")},
            },
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duty_status",
                    models.CharField(
                        choices=[
                            ("off_duty", "Off Duty"),
                            ("sleeper", "Sleeper Berth"),
                            ("driving", "Driving"),
                            ("on_duty", "On Duty (Not Driving)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration_minutes", models.IntegerField()),
                ("location", models.CharField(blank=True, max_length=500)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "daily_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="logs.dailylog",
                    ),
                ),
            ],
            options={
                "ordering": ["daily_log", "start_time"],
            },
        ),
    ]
