# Generated by Django 5.2.7 on 2025-10-10 10:33

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_location_address", models.CharField(max_length=500)),
                ("current_location_latitude", models.FloatField(blank=True, null=True)),
                (
                    "current_location_longitude",
                    models.FloatField(blank=True, null=True),
                ),
                ("pickup_location_address", models.CharField(max_length=500)),
                ("pickup_location_latitude", models.FloatField(blank=True, null=True)),
                ("pickup_location_longitude", models.FloatField(blank=True, null=True)),
                ("dropoff_location_address", models.CharField(max_length=500)),
                ("dropoff_location_latitude", models.FloatField(blank=True, null=True)),
                (
                    "dropoff_location_longitude",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "current_cycle_hours_used",
                    models.FloatField(
                        help_text="Hours already used in current 8-day cycle (0-70)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(70),
                        ],
                    ),
                ),
                (
                    "planned_start_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("total_distance_miles", models.FloatField(blank=True, null=True)),
                ("estimated_duration_hours", models.FloatField(blank=True, null=True)),
                ("days_required", models.IntegerField(blank=True, null=True)),
                (
                    "is_feasible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether driver has enough hours to complete this trip",
                    ),
                ),
                (
                    "feasibility_message",
                    models.TextField(
                        blank=True, help_text="Explanation if trip is not feasible"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
